name: AME
author: Vestri
description: ame
version: 0.11
api-version: 1.15
main: ame.java.AME
permissions:
  ame.admin:
    description: admin
    default: op
commands:
  amereload:
    description: reload events rewards...
    usage: /amereload
  amestartevent:
    description: start event
    usage: /amestartevent [eventname]
  ametl:
    description: start event
    usage: /ametl