name: AME
author: Vestri
description: ame
version: 0.22
api-version: 1.16
main: ame.java.AME
permissions:
  ame.admin:
    description: admin
    default: op
commands:
  amereload:
    description: reload events rewards...
    usage: /amereload
  amestartevent:
    description: start event
    usage: /amestartevent [eventname]
  ameshow:
    description: show active event
    usage: /ameshow