name: AME
author: Vestri
description: ame
version: 0.4
api-version: 1.15
main: ame.java.AME
permissions:
  ame.admin:
    description: admin
    default: op
commands:
  amereloadevent:
    description: reload events
    usage: /amereloadevent
  amestartevent:
    description: start event
    usage: /amestartevent [eventname]